#!/usr/bin/env python3
"""
reference_builder.py - Offline warp-path construction.

Pairs a constant-tempo score synthesis WAV with a real performance
recording (rehearsal or commercial release) via Multi-resolution
Multi-scale DTW (synctoolbox). The resulting warping path lets the
runtime follower take "the live position in the reference recording"
and recover the corresponding score position (and thus measure number).

Inputs:
    score_synth.wav    - generated by tasks/generate_score_wav.py
                         (or any other constant-tempo synthesis of the
                         same MusicXML).
    reference.wav      - real performance recording.

Outputs (saved into ``output_dir``):
    warping_path.npz   - keys:
                            ref_times    (K,) float32 — sec on reference
                            score_times  (K,) float32 — sec on synth
                            score_bpm           float  — synth tempo
                            feature_config      dict   — CENS parameters
    reference_cens.npy - (12, N_ref) float32 — pre-computed CENS for
                         the reference; the OLTW follower aligns the
                         live mic against this.

The synth is at a known constant BPM (default 120), so
``score_time → beat`` is just ``beat = score_time * bpm / 60``. Combined
with ScoreMapper.beat_to_measure, the follower can map any reference
time → measure number with one linear conversion and one binary search.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np

from audio_score_follower.core.feature_extractor import (
    FeatureConfig,
    compute_cens,
)

logger = logging.getLogger(__name__)


@dataclass
class BuildResult:
    """Return value of ``build_reference`` — useful for tests / plotting."""

    ref_times: np.ndarray       # (K,) float32, seconds on reference
    score_times: np.ndarray     # (K,) float32, seconds on synth
    reference_cens: np.ndarray  # (12, N_ref) float32
    score_cens: np.ndarray      # (12, N_score) float32 — kept for plotting
    score_bpm: float
    feature_config: FeatureConfig


def _load_wav_mono(path: Path, target_sr: int) -> np.ndarray:
    """Load a WAV at ``target_sr`` as mono float32."""
    import librosa  # type: ignore — heavy

    audio, _ = librosa.load(str(path), sr=target_sr, mono=True)
    return audio.astype(np.float32, copy=False)


def _run_mrmsdtw(
    score_cens: np.ndarray,
    ref_cens: np.ndarray,
    feature_rate: float,
) -> np.ndarray:
    """Run synctoolbox MrMsDTW, return warping path (2, K).

    Row 0: indices into score_cens; row 1: indices into ref_cens.

    We catch the import lazily and translate the import error into a
    clear hint, because synctoolbox installation can fail on systems
    missing libsndfile.
    """
    try:
        from synctoolbox.dtw.mrmsdtw import sync_via_mrmsdtw  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "synctoolbox is required for offline reference building.\n"
            "  → pip install synctoolbox\n"
            f"  (original error: {exc})"
        ) from exc

    logger.info(
        "Running MrMsDTW: score=(%d,%d) ref=(%d,%d) rate=%.2f Hz",
        score_cens.shape[0], score_cens.shape[1],
        ref_cens.shape[0], ref_cens.shape[1],
        feature_rate,
    )
    wp = sync_via_mrmsdtw(
        f_chroma1=score_cens,
        f_chroma2=ref_cens,
        input_feature_rate=feature_rate,
    )
    logger.info("MrMsDTW done, warp path length=%d", wp.shape[1])
    return np.asarray(wp, dtype=np.int64)


def build_reference(
    score_wav: Path,
    reference_wav: Path,
    output_dir: Path,
    *,
    score_bpm: float = 120.0,
    feature_config: Optional[FeatureConfig] = None,
    reference_start_offset_sec: float = 0.0,
    plot: bool = False,
) -> BuildResult:
    """Build offline artifacts from a score-synth WAV and a reference recording.

    Args:
        score_wav: WAV synthesised from the MusicXML at constant tempo.
        reference_wav: Real performance recording (any tempo).
        output_dir: Destination directory. Created if missing. Two files
            written: ``warping_path.npz`` and ``reference_cens.npy``.
        score_bpm: BPM used when synthesising ``score_wav``. Saved into
            the artifact so the runtime can derive score-time → beat
            without re-parsing the synth.
        feature_config: CENS parameters. None = use defaults. Must match
            what the runtime ``asf-follow`` uses; saved into the npz.
        reference_start_offset_sec: Seconds to trim from the head of the
            reference recording. Use this to drop conductor breath /
            chair noise that exist in the recording but not in the score
            — the DTW otherwise tries to align that to the score's first
            note and the whole path skews.
        plot: If True, also write ``warp_path.png`` into output_dir.

    Returns:
        BuildResult — primarily useful for tests / debugging.
    """
    cfg = feature_config or FeatureConfig()
    output_dir.mkdir(parents=True, exist_ok=True)

    logger.info("Loading score synth: %s", score_wav)
    score_audio = _load_wav_mono(score_wav, cfg.sample_rate)
    logger.info(
        "Score audio: %d samples (%.2f s @ %d Hz)",
        len(score_audio), len(score_audio) / cfg.sample_rate, cfg.sample_rate,
    )

    logger.info("Loading reference recording: %s", reference_wav)
    ref_audio = _load_wav_mono(reference_wav, cfg.sample_rate)
    if reference_start_offset_sec > 0:
        skip = int(reference_start_offset_sec * cfg.sample_rate)
        if skip >= len(ref_audio):
            raise ValueError(
                f"reference_start_offset_sec={reference_start_offset_sec} "
                f"exceeds reference duration {len(ref_audio)/cfg.sample_rate:.2f}s"
            )
        logger.info(
            "Trimming %.3fs (%d samples) from reference head",
            reference_start_offset_sec, skip,
        )
        ref_audio = ref_audio[skip:]
    logger.info(
        "Reference audio: %d samples (%.2f s)",
        len(ref_audio), len(ref_audio) / cfg.sample_rate,
    )

    logger.info("Computing CENS for score synth …")
    score_cens = compute_cens(score_audio, cfg)
    logger.info("Computing CENS for reference …")
    ref_cens = compute_cens(ref_audio, cfg)
    logger.info(
        "CENS shapes: score=%s ref=%s (rate=%.2f Hz)",
        score_cens.shape, ref_cens.shape, cfg.effective_frame_rate(),
    )

    wp = _run_mrmsdtw(score_cens, ref_cens, cfg.effective_frame_rate())
    # wp is (2, K); convert frame indices → seconds on each axis.
    frame_to_sec = 1.0 / cfg.effective_frame_rate()
    score_times = (wp[0].astype(np.float64) * frame_to_sec).astype(np.float32)
    ref_times = (wp[1].astype(np.float64) * frame_to_sec).astype(np.float32)
    # Re-add the trimmed offset to ref_times so callers reason in the
    # *original* recording timeline. (The OLTW at runtime operates on
    # the trimmed CENS — but if the user replays the original WAV they
    # expect ref_time to match the original timestamps.)
    if reference_start_offset_sec > 0:
        ref_times = ref_times + reference_start_offset_sec

    # Ensure monotonic non-decreasing — MrMsDTW guarantees it but be defensive.
    if not np.all(np.diff(ref_times) >= 0) or not np.all(np.diff(score_times) >= 0):
        logger.warning("Warp path is not monotonic; sorting defensively")
        order = np.argsort(ref_times)
        ref_times = ref_times[order]
        score_times = score_times[order]

    # Persist
    warp_path = output_dir / "warping_path.npz"
    np.savez(
        warp_path,
        ref_times=ref_times,
        score_times=score_times,
        score_bpm=np.float32(score_bpm),
        feature_config=np.array(
            [cfg.sample_rate, cfg.hop_length, cfg.cens_win, cfg.norm],
            dtype=np.float32,
        ),
        feature_config_quant_steps=np.array(cfg.quant_steps, dtype=np.int32),
    )
    logger.info("Saved warping path → %s", warp_path)

    cens_path = output_dir / "reference_cens.npy"
    np.save(cens_path, ref_cens)
    logger.info("Saved reference CENS → %s (%.1f MB)",
                cens_path, cens_path.stat().st_size / 1024 / 1024)

    # Also save a small JSON sidecar with feature config — easier to
    # diff / debug than reading the npz.
    import json
    meta = {
        "score_bpm": float(score_bpm),
        "reference_start_offset_sec": float(reference_start_offset_sec),
        "feature_config": cfg.to_dict(),
        "reference_duration_sec": float(len(ref_audio) / cfg.sample_rate),
        "warp_path_length": int(wp.shape[1]),
    }
    meta_path = output_dir / "build_meta.json"
    meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False))
    logger.info("Saved metadata → %s", meta_path)

    if plot:
        _plot_warp(score_cens, ref_cens, wp, output_dir, cfg)

    return BuildResult(
        ref_times=ref_times,
        score_times=score_times,
        reference_cens=ref_cens,
        score_cens=score_cens,
        score_bpm=score_bpm,
        feature_config=cfg,
    )


def _plot_warp(
    score_cens: np.ndarray,
    ref_cens: np.ndarray,
    wp: np.ndarray,
    output_dir: Path,
    cfg: FeatureConfig,
) -> None:
    """Save a warp-path visualization PNG. Optional dependency on matplotlib."""
    try:
        import matplotlib.pyplot as plt  # type: ignore
    except ImportError:
        logger.warning("matplotlib not installed; skipping --plot")
        return

    fr = cfg.effective_frame_rate()
    fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=False)

    axes[0].imshow(
        score_cens, aspect="auto", origin="lower", interpolation="nearest",
        extent=[0, score_cens.shape[1] / fr, 0, 12],
    )
    axes[0].set_title("Score-synth CENS")
    axes[0].set_xlabel("Score time (s)")
    axes[0].set_ylabel("Pitch class")

    axes[1].imshow(
        ref_cens, aspect="auto", origin="lower", interpolation="nearest",
        extent=[0, ref_cens.shape[1] / fr, 0, 12],
    )
    axes[1].plot(wp[1] / fr, wp[0] / fr * 12 / max(1, score_cens.shape[1] / fr),
                 color="red", linewidth=0.8)
    axes[1].set_title("Reference CENS + warp path (red = score time scaled to 0-12)")
    axes[1].set_xlabel("Reference time (s)")

    fig.tight_layout()
    out = output_dir / "warp_path.png"
    fig.savefig(out, dpi=110)
    plt.close(fig)
    logger.info("Saved plot → %s", out)
